Repository jenkinsci/workflow-step-api-plugin, pull requests merged in 2021-12, with the labels that each got.

#73 `DynamicContext.Typed` did not correctly handle queries of subtypes
  src/main/java/org/jenkinsci/plugins/workflow/steps/DynamicContext.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/DynamicContextTest.java
Labels: bug

#71 Miscellaneous code cleanup
  src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractSynchronousStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/ContextParameterModule.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/DynamicContext.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/MissingContextVariableException.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/structs/DescribableHelper.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImplTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecutionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecutionTest.java
Labels: maintenance

#69 Use container agent in `Jenkinsfile` and test on Java 11
  Jenkinsfile
Labels: tests

#74 enable cd
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: internal

#62 Update plugin POM and BOM
  pom.xml
Labels: dependencies

#75 clean up readme and changelog
  CHANGELOG.md
  README.md
Labels: documentation

#65 Reduce usages of Guava
  src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/StepDescriptor.java
Labels: internal

#64 Fix typo in CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#77 `SynchronousResumeNotSupportedException` as a marker for lack of JENKINS-30383
  src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractSynchronousNonBlockingStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/GeneralNonBlockingStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousResumeNotSupportedException.java
Labels: enhancement
