Repository jenkinsci/workflow-step-api-plugin, pull requests merged in 2022-07, with the labels that each got.

#112 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#105 Make a comment more inclusive
  src/main/java/org/jenkinsci/plugins/workflow/steps/StepContext.java
Labels: documentation

#124 [JENKINS-49707] Recommend `BodyExecution.cancel` overload taking `Throwable`
  src/main/java/org/jenkinsci/plugins/workflow/steps/BodyExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousStepExecution.java
Labels: developer
