Repository jenkinsci/workflow-step-api-plugin, pull requests merged in 2024-01, with the labels that each got.

#148 Forward compatibility with Guice 7
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepDescriptorImpl.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImpl.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/AbstractStepImplTest.java
Labels: dependencies

#149 Improved `StepExecutions`, available outside test scope
  src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecutions.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/StepExecutions.java
Labels: enhancement

#150 Link to `StepExecutions` in relevant Javadoc
  src/main/java/org/jenkinsci/plugins/workflow/steps/BodyExecutionCallback.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/Step.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/StepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousNonBlockingStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/SynchronousStepExecution.java
Labels: documentation
